apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    vendor: "dorshaar"
  name: tasker-amq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasker-amq
  template:
    metadata:
      labels:
        app: tasker-amq
    spec:  
      containers:
      - name: tasker-amq
        image: activemq-consumer:1.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            memory: 1500Mi
        ports:
        - containerPort: 80
