apiVersion: v1
kind: Service
metadata:
  labels:
    vendor: dorshaar
  name: tasker-amq
  namespace: default
spec:
  ports:
  - name: openwire
    port: 61616
    protocol: TCP
    targetPort: 61616
  - name: ui
    port: 8161
    protocol: TCP   
  selector:
    app: tasker-amq
  sessionAffinity: None
  type: NodePort