// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tasker.Infra.Persistence.Context.AppDbContext.LoadDatabase~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tasker.Api.Controllers.NotesController.GetGeneralNoteAsync(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Takser.Api.Controllers.TasksGroupsController.PostGroupAsync(System.String,Tasker.App.Resources.TasksGroupResource)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Takser.Api.Controllers.TasksGroupsController.PutWorkTaskAsync(Tasker.App.Resources.TasksGroupResource)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Takser.Api.Controllers.TasksGroupsController.RemoveGroup(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tasker.Api.Controllers.NotesController.GetPrivateNoteAsync(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tasker.Infra.Persistence.Context.AppDbContext.SaveCurrentDatabase~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tasker.Infra.Services.TasksGroupService.MoveTaskAsync(System.String,System.String)~System.Threading.Tasks.Task{Tasker.Domain.Communication.IResponse{TaskData.Contracts.IWorkTask}}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tasker.Infra.Services.TasksGroupService.RemoveAsync(System.String)~System.Threading.Tasks.Task{Tasker.Domain.Communication.IResponse{TaskData.Contracts.ITasksGroup}}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tasker.Infra.Services.TasksGroupService.RemoveTaskAsync(System.String)~System.Threading.Tasks.Task{Tasker.Domain.Communication.IResponse{TaskData.Contracts.IWorkTask}}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tasker.Infra.Services.TasksGroupService.SaveAsync(System.String)~System.Threading.Tasks.Task{Tasker.Domain.Communication.IResponse{TaskData.Contracts.ITasksGroup}}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tasker.Infra.Services.TasksGroupService.SaveTaskAsync(System.String,System.String)~System.Threading.Tasks.Task{Tasker.Domain.Communication.IResponse{TaskData.Contracts.IWorkTask}}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tasker.Infra.Services.TasksGroupService.UpdateGroupAsync(System.String,System.String)~System.Threading.Tasks.Task{Tasker.Domain.Communication.IResponse{TaskData.Contracts.ITasksGroup}}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tasker.Infra.Services.TasksGroupService.UpdateTaskAsync(Tasker.App.Resources.WorkTaskResource)~System.Threading.Tasks.Task{Tasker.Domain.Communication.IResponse{TaskData.Contracts.IWorkTask}}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Takser.Api.Controllers.WorkTasksController.PostTaskAsync(System.String,Tasker.App.Resources.WorkTaskResource)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Takser.Api.Controllers.WorkTasksController.PutWorkTaskAsync(Tasker.App.Resources.WorkTaskResource)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Takser.Api.Controllers.WorkTasksController.RemoveTask(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tasker.Api.Middlewares.ExceptionHandlingMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext)~System.Threading.Tasks.Task")]
